run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - noctx
    - bodyclose
    - contextcheck
    - sqlclosecheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/ilramdhan/goxynhub
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning

issues:
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
  max-issues-per-linter: 50
  max-same-issues: 10
